### ISSUE TITLE
Result List page explanations have the incorrect parameter symbol

### ISSUE THREAD

**Issue by erikspears** [sidprobstein/swirl-search#24]
On the SWIRL Results List page (http://localhost:8000/swirl/results/?search_id=*), there is a block of test at the top of the page that outlines additional parameters that can be added the Results List URL to reveal additional information.  Three of these explanations indicate that the question mark (?) is required before adding the additional parameter:
- ?result_mixer=
- ?explain=
- ?provider=

As seen here:
![Result list text](https://user-images.githubusercontent.com/98238295/192119148-8048e207-55d8-44e3-82f5-064379e61d16.png)

This is incorrect for these 3 options; instead, they require the ampersand (&) before the parameter.  For example,  `&explain=true` is correct and activates query explanation within the Result Lis, whereas `?explain=true` gives a 500 error.

The code responsible for generating the text at the top of the Result List page should be update such that the ampersand is presented to users for these 3 options.

**Comment by sidprobstein** [comment]
Fixed in 1.3_final!

**Comment by erikspears** [comment]
Fixed in 1.3 Final.  Updated text instructions validated:
![Result List text - fixed](https://user-images.githubusercontent.com/98238295/192153933-fba13bc8-45f0-4b19-86e8-253628f66f6c.png)
