### ISSUE TITLE
Release Notes for v. 1.3 - updates needed

### ISSUE THREAD

**Issue by erikspears** [sidprobstein/swirl-search#25]
There are 2 items on the v. 1.3 Release Notes that might need attention.

1. Under "Known Issues" > first issue > third line:  the "rerun function" link returns a 404; the href should be corrected.
2. Unser "Known Issues" > second issue:  the reference page in Django Admin (for managing results objects) does NOT appear to be returning a 404.  Perhaps this can be removed as a known issue, if confirmed?
Link in the release notes:  http://localhost:8000/admin/swirl/result/
...opens this page:
![Django admin - results](https://user-images.githubusercontent.com/98238295/192120154-422f2c35-d229-4331-8bd3-baa9d4c3f045.png)

**Comment by sidprobstein** [comment]
Fixed in 1.3_final

**Comment by erikspears** [comment]
Confirmed, fixed in 1.3 Final
