### ISSUE TITLE
Incorrect links:  Readme and Quick Start pages

### ISSUE THREAD

**Issue by erikspears** [sidprobstein/swirl-search#26]
**On the Homepage / Readme**
- “Result mixers” link in the 5th bullet under "Features" goes to the top of the User Guide, not to the Result Mixers section:  https://github.com/sidprobstein/swirl-search/wiki/2.-User-Guide#mixers
- “to-do list” link under "Contributing" returns a 404:  https://github.com/sidprobstein/swirl-search/blob/main/docs/TO_DO.md
- "Documentation" section, those links are the only one that display horizontally; were they supposed to be a vertical, bulleted list?

**On the Quick Start page**
- "Next Steps" section, the “Relevancy Explanation” link leads to raw content version of the page, here: https://raw.githubusercontent.com/wiki/sidprobstein/swirl-search/2.-User-Guide.md#relevancy-explanation

**Comment by sidprobstein** [comment]
Fixed in main, will be released in 1.3_final, THANK YOU!

**Comment by erikspears** [comment]
Fixed in 1.3 Final
