### ISSUE TITLE
Django Admin page > View Site link returns "Not Found"

### ISSUE THREAD

**Issue by erikspears** [sidprobstein/swirl-search#27]
To see this issue:
- Click the "Admin" link from the main SWIRL page to access the Django Admin area.
- On the top right of that page, click the "View Site" link.

This returns a page "Not Found" message at this URL:  http://localhost:8000/

Perhaps this link should take the user back to the main SWIRL homepage?  http://localhost:8000/swirl/

**Comment by sidprobstein** [comment]
Fixed in 1.3_final! Great catch

**Comment by erikspears** [comment]
Fixed in 1.3 Final
