### ISSUE TITLE
Newsdata.io Search Provider setup throws an error

### ISSUE THREAD

**Issue by erikspears** [sidprobstein/swirl-search#28]
Attempting to add the Newsdata.io source as a Search Provider per the User Guide > Copy/Paste Install instructions using the JSON here (1.3 Final):  https://github.com/sidprobstein/swirl-search/blob/main/SearchProviders/newsdata_api.json

After the copy/paste and clicking POST, as documented, the Search Provider List page (http://localhost:8000/swirl/searchproviders/) returns an error:
```
{
    "non_field_errors": [
        "Invalid data. Expected a dictionary, but got list."
    ]
}
```

See here:
![Newsdata setup error](https://user-images.githubusercontent.com/98238295/192172384-0609a4ca-81f6-428b-86ae-6cd8efa00462.png)

**Comment by sidprobstein** [comment]
Thanks @erikspears for this report; this will be released this weekend as part of 1.5

**Comment by sidprobstein** [comment]
Fix is confirmed

**Comment by erikspears** [comment]
Hi @sidprobstein ,

Attempting to validate the fix in 1.5 (pulled yesterday), and I'm still seeing errors.  Might be simply syntax in the example JSON though?

In 1.5 > SearchProviders > newsdata_api.json (https://github.com/sidprobstein/swirl-search/blob/main/SearchProviders/newsdata_api.json) ... you have square brackets enclosing the JSON, which is unique for the examples, it seems.

If I copy that block and attempt a copy/paste (RAW Data) new SearchProvider, I still get this error:
<img width="530" alt="Newsdata - 1 5 error creating" src="https://user-images.githubusercontent.com/98238295/199327069-afe9305c-3303-4e76-99fd-3e7648f30f90.png">

If I ignore the square brackets and attempt the same, I get this error:
<img width="562" alt="Newsdata - 1 5 error creating 2" src="https://user-images.githubusercontent.com/98238295/199327177-3fe1f2ea-5b57-48fa-9673-8daa0a7976b0.png">

Perhaps something is still off a bit with the example JSON for this one?

**Comment by sidprobstein** [comment]
@erikspears good catch, you are right. The SearchProvider is the issue. I forgot to migrate the response mappings out of the result_mappings ...

Old/bad:
result_mappings": "body=description,url=link,date_published=pubDate,author=creator,source_id,NO_PAYLOAD,FOUND=totalResults,RESULTS=results"

New/good:
    "response_mappings": "FOUND=totalResults,RESULTS=results",
    "result_mappings": "body=description,url=link,date_published=pubDate,author=creator,source_id,NO_PAYLOAD",

Just pushed the new provider json https://github.com/sidprobstein/swirl-search/blob/main/SearchProviders/newsdata_api.json

**Comment by erikspears** [comment]
Re-opening, still lingering issues here.

There are actually 2 sources in the example JSON.  The first of these can be successfully added as a SearchProvider, however searches still error out:
```
        "RequestsGet_5_4: Error: request.get returned: 401 UNAUTHORIZED from: Latest News (web/newsdata.io) for: https://newsdata.io/api/1/news?language=en&apikey=newsdata-api-key-here&q=mastodon",
        "RequestsGet_5_4: Error: request.get returned: 401 UNAUTHORIZED from: Latest News (web/newsdata.io) for: https://newsdata.io/api/1/news?language=en&apikey=newsdata-api-key-here&q=mastodon",
```

More investigation is under way...

**Comment by sidprobstein** [comment]
Just pushed an update to the json that disables the second provider. The default (free) access key does not include the archive. More here: https://newsdata.io/pricing
