### ISSUE TITLE
The CLI help for swirl.py isn't working correctly (MacOS)

### ISSUE THREAD

**Issue by erikspears** [sidprobstein/swirl-search#42]
Doing either of the following in the `swirl-directory` results in the same output to the terminal window.
`./swirl.py -h
`
`./swirl.py -help
`

Output to the Terminal window:

<img width="629" alt="Swirl_py help" src="https://user-images.githubusercontent.com/98238295/199334049-48029634-68f1-4f4e-8b33-27e4c748b60a.png">

**Comment by sidprobstein** [comment]
@erikspears Excellent catch. The workaround is:

```
python swirl.py help
```

**Comment by sidprobstein** [comment]
-h is not supported for py, see workaround above
