### ISSUE TITLE
Clean-up:  Remove celery beat?

### ISSUE THREAD

**Issue by erikspears** [sidprobstein/swirl-search#49]
Technical clean-up discussion / task:  remove celery beat?

CC:  @sidprobstein and @dnicodemus

**Comment by dnicodemus** [comment]
Is there a reason to keep the references to Celery Beat around?

**Comment by sidprobstein** [comment]
Celery Beat is used for the retention policy https://github.com/sidprobstein/swirl-search/wiki/2.-User-Guide#expiration and will support the search.subscription property planned for a future release...
