### ISSUE TITLE
Swirl can't talk to rabbitmq

### ISSUE THREAD

**Issue by joshsgoldstein** [sidprobstein/swirl-search#56]
celery cannot talk to rabbitmq and is throwing this error

Here is the error: 
amqp.exceptions.InternalError: Connection.open: (541) INTERNAL_ERROR - access to vhost '/' refused for user 'guest': vhost '/' is down

**Comment by sidprobstein** [comment]
This appears to be a corrupt rabbit. To fix:

Follow the steps at the bottom of this page:
 [https://jfrog.com/knowledge-base/why-do-i-get-no-access-to-this-vhost-when-trying-to-start-the-rabbitmq/](https://jfrog.com/knowledge-base/why-do-i-get-no-access-to-this-vhost-when-trying-to-start-the-rabbitmq/)

The commands may need adaptation for OS/X, but work on ubuntu!
