### ISSUE TITLE
Error:  PostgreSQL_7_6: Error: name 'psycopg2' is not defined

### ISSUE THREAD

**Issue by erikspears** [sidprobstein/swirl-search#57]
Running v. 1.5, I got the Postgresql funding example from docs all setup and working.  It was returning results as expected.

I then pulled the 1.6rc branch down to a separate directory.  I stopped SWIRL 1.5 and installed 1.6rc.  Postgres itself was still running the whole time.  No other SWIRL dependencies were uninstalled.

I setup the SP in 1.6rc for the Postgres funding example, then ran a search and got this error on the Results List:
`PostgreSQL_7_6: Error: name 'psycopg2' is not defined`

```
This is odd because pip knows all about psycopg2 already:
% pip show psycopg2 
Name: psycopg2
 Version: 2.9.5 S
ummary: psycopg2 - Python-PostgreSQL Database Adapter
 Home-page: https://psycopg.org/ 
Author: Federico Di Gregorio 
Author-email: fog@initd.org L
icense: LGPL with exceptions 
Location: /Users/erikspears/.pyenv/versions/3.9.9/lib/python3.9/site-packages
Requires:  
Required-by:  
```

Restarting SWIRL did not get rid of the error.  Instead, I had to uninstall and reinstall `psycopg2` (using PIP).  That error is no longer returned; and I am getting results from the Postgres funding example, as expected.

While there is a work-around, it would be good to know why that error was thrown in the first place.  And if it will happen with a proper upgrade from 1.5 -> 1.6 vs. pulling the 1.6rc branch separately.

**Comment by sidprobstein** [comment]
Dupe; assigned to Josh
