### ISSUE TITLE
Django UI returns only the search providers list when asking for pages beyond the last result

### ISSUE THREAD

**Issue by erikspears** [sidprobstein/swirl-search#8]
At present, SWIRL has a limit of 10 results per search provider.  So, when querying the 3 pre-set GSE providers, users can get a max of 30 results.  In the Django UI, users can ask for additional pages beyond the max hits returned (e.g. by adding `&page=5` to the results URL), and the UI will return a `HTTP 200 OK` page with only the search providers listed.  This occurs anytime the user asked for a page beyond the one containing the last result.  This scenario is potentially confusing for users.

Is it possible for the Django UI to return a more user-friendly message indicating that the maximum number of results has been exceeded?  Or, perhaps even just what the max number of hits for the given query was?  It's also unclear if having the search providers returned in this case is useful.

Labeling as a possible enhancement, @sidprobstein

**Comment by sidprobstein** [comment]
Resolved by SWIRL SEARCH 1.1
