### ISSUE TITLE
Swirl 1.8RC:  Swagger API link is 404

### ISSUE THREAD

**Issue by erikspears** [sidprobstein/swirl-search#85]
From the Swirl homepage in v. 1.8RC, the "Swagger" link is 404.

<img width="1006" alt="Swagger 404 in 1-8rc" src="https://user-images.githubusercontent.com/98238295/212198774-b66d4c3e-8a0d-4e4f-820c-94eeb2e99f73.png">

Link URL:  http://localhost:8000/swagger-ui/

Re-checked in v. 1.7, working there.  The issue is new to 1.8RC

**Comment by sidprobstein** [comment]
Fixed in 1.8

**Comment by erikspears** [comment]
Verified fixed in 1.8, closing.
