### ISSUE TITLE
Docker warnings for unresolved variable in compose file

### ISSUE THREAD

**Issue by erikspears** [sidprobstein/swirl-search#89]
When running the `docker compose up` with Swirl v. 1.8, we see these Warnings, courtesy of Docker:
```
swirl1-8rc % docker compose up
WARN[0000] The "jjf" variable is not set. Defaulting to a blank string. 
WARN[0000] The "jjf" variable is not set. Defaulting to a blank string. 
WARN[0000] The "jjf" variable is not set. Defaulting to a blank string. 
```

They are just warnings and don't disrupt bringing up Swirl.

This behavior seems to be similar to this issue filed in the `compose-cli` project:  https://github.com/docker/compose-cli/issues/1907

Specifically this comment:  https://github.com/docker/compose-cli/issues/1907#issuecomment-878020499

Filing this issue as tech-debt so that we can track this and potentially sort it out in future.

**Comment by sidprobstein** [comment]
This is resolved by 1.8.1
