### ISSUE TITLE
Stack2Mixer produces 500 error in 1.8

### ISSUE THREAD

**Issue by erikspears** [sidprobstein/swirl-search#95]
Stack2Mixer (and other "stack" mixers) produce 500 error in 1.8.

**Comment by sidprobstein** [comment]
This is fixed in 1.8.1

**Comment by sidprobstein** [comment]
https://github.com/sidprobstein/swirl-search/releases/tag/v1.8.1

**Comment by erikspears** [comment]
Validated working in 1.8.1 Docker, thanks for the quick fix @sidprobstein !
