### ISSUE TITLE
why do you use Elastic Search

### ISSUE THREAD

**Issue by MaryLilian** [sidprobstein/swirl-search#99]
Hi, I am reading your project and I love this project
I have a question, why do you choose Elastic search in your project instead of others like Redis Search or Full text search extension for RDBMS , are there any special features that others dont have it. Can you share me it. I am wondering when I should choose KubeMQ instead of others like Redis Search or Full text search extension

**Comment by sidprobstein** [comment]
Hi! Thanks for commenting. We support Elastic, OpenSearch and Apache SOLR, plus PostgreSQL and Google BigQuery. Grab the repo right here: https://github.com/sidprobstein/swirl-search connectors are here: https://github.com/sidprobstein/swirl-search/tree/main/swirl/connectors

Best,
--Sid
